# Generated by Django 4.2.7 on 2025-09-24 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('prise', 'Prise de clés'), ('remise', 'Remise de clés')], max_length=10, verbose_name="Type d'activité")),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('carburant_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carburant (litres)')),
                ('carburant_pourcentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Carburant (%)')),
                ('recette_jour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recette du jour (€)')),
                ('etat_vehicule', models.TextField(blank=True, null=True, verbose_name='État du véhicule')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Signature')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('severite', models.CharField(choices=[('mineure', 'Mineure'), ('moderee', 'Modérée'), ('majeure', 'Majeure'), ('critique', 'Critique')], default='mineure', max_length=10, verbose_name='Sévérité')),
                ('statut', models.CharField(choices=[('signalee', 'Signalée'), ('en_cours', 'En cours de réparation'), ('reparée', 'Réparée'), ('annulee', 'Annulée')], default='signalee', max_length=10, verbose_name='Statut')),
                ('cout_reparation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût de réparation (€)')),
                ('date_reparation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réparation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activite', verbose_name='Activité liée')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-date'],
                'unique_together': {('chauffeur', 'date')},
            },
        ),
    ]
