# Generated by Django 4.2.7 on 2025-09-24 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['-date_heure'], 'verbose_name': 'Activité (Legacy)', 'verbose_name_plural': 'Activités (Legacy)'},
        ),
        migrations.CreateModel(
            name='RemiseCles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_remise', models.TimeField(verbose_name='Heure de remise')),
                ('recette_realisee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recette réalisée (FCFA)')),
                ('plein_carburant', models.BooleanField(default=False, verbose_name='Plein de carburant')),
                ('probleme_mecanique', models.CharField(default='Aucun', max_length=200, verbose_name='Problème mécanique')),
                ('signature', models.TextField(verbose_name='Signature électronique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Remise de clés',
                'verbose_name_plural': 'Remises de clés',
                'ordering': ['-date', '-heure_remise'],
                'unique_together': {('chauffeur', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriseCles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_prise', models.TimeField(verbose_name='Heure de prise')),
                ('objectif_recette', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif de recette (FCFA)')),
                ('plein_carburant', models.BooleanField(default=False, verbose_name='Plein de carburant')),
                ('probleme_mecanique', models.CharField(default='Aucun', max_length=200, verbose_name='Problème mécanique')),
                ('signature', models.TextField(verbose_name='Signature électronique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Prise de clés',
                'verbose_name_plural': 'Prises de clés',
                'ordering': ['-date', '-heure_prise'],
                'unique_together': {('chauffeur', 'date')},
            },
        ),
    ]
