# Generated by Django 4.2.7 on 2025-09-25 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
        ('activities', '0002_alter_activite_options_remisecles_prisecles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('prise', 'Prise de clés'), ('remise', 'Remise de clés')], max_length=10, verbose_name="Type d'activité")),
                ('date_activite', models.DateField(verbose_name="Date de l'activité")),
                ('donnees_originales', models.JSONField(verbose_name='Données originales')),
                ('nouvelles_donnees', models.JSONField(verbose_name='Nouvelles données')),
                ('raison', models.TextField(verbose_name='Raison de la modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name="Commentaire de l'admin")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('admin_traite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin qui a traité')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.chauffeur', verbose_name='Chauffeur')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
