# Generated by Django 4.2.7 on 2025-09-25 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si le chauffeur est actif dans le système', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du profil chauffeur', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='email',
            field=models.EmailField(help_text='Adresse email de contact', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom',
            field=models.CharField(help_text='Nom de famille du chauffeur', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='prenom',
            field=models.CharField(help_text='Prénom du chauffeur', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone (format international accepté)', max_length=15, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur Django associé', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterModelTable(
            name='chauffeur',
            table='drivers_chauffeur',
        ),
    ]
