# Generated by Django 4.2.7 on 2025-11-11 21:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0004_assignationsuperviseur'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignationsuperviseur',
            name='drivers_assignationsuperviseur_unique_chauffeur_superviseur',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si le chauffeur est actif', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du profil', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email du chauffeur (optionnel)', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom',
            field=models.CharField(help_text='Nom de famille du chauffeur', max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='prenom',
            field=models.CharField(help_text='Prénom du chauffeur', max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone au format gabonais', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format gabonais (+241XXXXXXXX ou 0XXXXXXXX)', regex='^(\\+241|0)[0-9]{8}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='user',
            field=models.OneToOneField(default=1, help_text='Utilisateur Django associé à ce chauffeur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignationsuperviseur',
            unique_together={('chauffeur', 'superviseur')},
        ),
    ]
